### PR TITLE
Cat fixes

### PR DESCRIPTION
**Pull request by jcrist**
Based on PR#150. Fixed merge conflicts and long repr. Feel free to use or toss.

### CODE REVIEW

**Comment by cpcloud** [comment]
@jcrist can you rebase off of 8d1293f and the re submit the PR to my `cat` branch? thx

**Comment by jcrist** [comment]
Done.

**Comment by cpcloud** [comment]
looks like the PR is still against my `master` can you submit it against my `cat` branch?

**Comment by jcrist** [comment]
oh, woops. yes.

**Pull request closed without merging**
